"""empty message

Revision ID: 85749c0c4589
Revises: b3ff59df2833
Create Date: 2022-04-08 07:46:57.160792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85749c0c4589'
down_revision = 'b3ff59df2833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'image',
               existing_type=mysql.VARCHAR(length=20000),
               type_=sa.TEXT(length=20000000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'image',
               existing_type=sa.TEXT(length=20000000),
               type_=mysql.VARCHAR(length=20000),
               existing_nullable=True)
    # ### end Alembic commands ###
